# -*- coding: utf-8 -*-
"""apples_and_oranges_SVC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HfLYqfaYHtBuUm02IcPS2AKK8ga4bs0D
"""

import pandas as p

data=p.read_csv("Loan.csv")
data.head(20)

data2=p.read_csv("apples_and_oranges.csv")
data2.head(20)

data3=p.get_dummies(data2['Class'])
data3

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

encoder=OneHotEncoder(sparse_output=False)

encoded=encoder.fit_transform(data2[['Class']])
encoded

dependent= p.DataFrame(encoded)



from sklearn.svm import LinearSVC
x=data2[['apple','orange']]
y