# -*- coding: utf-8 -*-
"""fetalhealthSVC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HfLYqfaYHtBuUm02IcPS2AKK8ga4bs0D
"""

import pandas as p

data=p.read_csv("fetal_health.csv")
data.head(20)

# Normal-1
# Suspect-2
# Pathological-3

data.info()

data.describe()

from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest=train_test_split(data.drop(['fetal_health'],axis=1),data['fetal_health'],test_size=0.3,random_state=42)

print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

from sklearn import preprocessing

scaler=preprocessing.StandardScaler()

xtrain_scaled=scaler.fit_transform(xtrain)
xtest_scaled=scaler.fit_transform(xtest)

from sklearn.svm import LinearSVC

model=LinearSVC()
model.fit(xtrain_scaled,ytrain)

predictions = model.predict(xtest_scaled)
print(predictions)

decision_values = model.decision_function(xtest_scaled)
print(decision_values)